export const s = {
  footer: "text-white py-12 relative overflow-hidden border-t-8 border-yellow-600",
  texture1: "absolute inset-0 opacity-[0.08] bg-[url('https://www.transparenttextures.com/patterns/dark-matter.png')]",
  texture2: "absolute inset-0 opacity-[0.05] bg-[url('https://www.transparenttextures.com/patterns/vintage-wallpaper.png')]",
  inner: "container mx-auto px-4 relative z-10",
  content: "flex flex-col md:flex-row items-center justify-between gap-8",
  logoWrapper: "flex items-center gap-4",
  logo: "h-24 w-auto opacity-90 hover:opacity-100 transition-opacity",
  nav: "flex flex-col md:flex-row items-center gap-6 md:gap-8",
  navLink: "text-white hover:text-yellow-400 transition-all duration-500 font-serif text-xl",
  navSeparator: "hidden md:inline text-yellow-600 text-xl",
  contactCol: "flex flex-col items-center md:items-end gap-3",
  contactLabel: "text-sm text-white/70 uppercase tracking-widest font-serif italic",
  contactLink: "flex items-center gap-2 text-base md:text-lg text-white hover:text-yellow-400 transition-all duration-300 group",
  contactIcon: "w-5 h-5 group-hover:scale-110 transition-transform",
  contactEmail: "group-hover:underline",
  bottom: "mt-8 pt-6 text-center space-y-3",
  copyright: "text-base text-yellow-100/50 font-serif",
  dedication: "text-sm text-yellow-100/40 font-serif italic",
} as const;
