export const s = {
  replyIndent: "ml-12 border-l-2 border-stone-200 pl-4",
  reviewCard: "bg-white p-4 rounded border border-stone-200",
  header: "flex items-start justify-between mb-3",
  headerLeft: "flex items-start gap-3",
  avatar:
    "w-10 h-10 rounded-full overflow-hidden border border-yellow-600/30 bg-primary shrink-0",
  avatarImg: "w-full h-full object-cover",
  avatarImgDefault: "scale-[2] translate-x-0.5 translate-y-1.5",
  authorName: "font-semibold text-stone-900",
  timestamp: "text-xs text-stone-500",
  deleteBtn: "text-red-600 hover:text-red-700 hover:bg-red-50",
  content: "text-stone-700 whitespace-pre-wrap mb-3",
  actions: "flex items-center gap-4",
  likeBtn: "flex items-center gap-1",
  likedHeart: "w-4 h-4 fill-current",
  unlikedHeart: "w-4 h-4",
  likeBtnActive: "text-red-500",
  likeBtnInactive: "text-stone-500",
  replyBtn: "flex items-center gap-1 text-stone-500 hover:text-stone-700",
  replyForm: "mt-4 space-y-2",
  replyTextarea: "min-h-[80px] border-stone-300 focus:ring-yellow-500",
  replyActions: "flex gap-2",
  replies: "space-y-3",
  inlineText: "text-sm",
} as const;
